const test=require('node:test'),assert=require('node:assert/strict'),G=require('../assets/core.js'),T=require('../assets/transfer.js');
const builtin={id:'ex-001',name:'Bankdrücken',kind:'reps',muscle:'Brust',equipment:'Langhantel',instructions:['Kontrolliert bewegen.']};
const custom={id:'mine',name:'Übung 🏋️ <img src=x>',kind:'time',muscle:'Ganzkörper',equipment:'Eigengewicht',instructions:['Eigene Anleitung'],custom:true};
function template(){return{id:'existing-id',name:'Training 🏃 Österreich',category:'Kraft',notes:'private Notiz',items:[G.item(builtin,2,120),G.item(custom,1,0)]};}
test('Datei und Code erhalten Unicode, eigene Übungen und Trainingswerte; private Angaben nur auf Wunsch',()=>{const t=template();t.items[0].sets[0].weight=42.5;t.items[0].sets[0].rpe=8;const bundle=T.pack(t,'template',[builtin,custom]);assert.equal(bundle.workout.notes,'');assert.equal(bundle.workout.items[0].sets[0].rpe,'');const code=T.code(bundle);assert.ok(code.startsWith('SW1.'));assert.deepEqual(T.parse(code),T.parse(T.json(bundle)));const result=T.prepareImport(T.parse(code),'template',[builtin]);assert.notEqual(result.record.id,t.id);assert.equal(result.record.items[0].exerciseId,builtin.id);assert.equal(result.record.items[0].sets[0].weight,42.5);assert.equal(result.record.items[0].sets[0].done,false);assert.notEqual(result.record.items[1].exerciseId,custom.id);assert.equal(result.customExercises[0].name,custom.name);assert.equal(result.customExercises.length,1);const personal=T.pack(t,'template',[builtin,custom],true);assert.equal(personal.workout.notes,t.notes);assert.equal(personal.workout.items[0].sets[0].rpe,8);});
test('Einheiten können als Vorlage oder Verlauf importiert werden; Cardio erhält Distanz und Höhenmeter',()=>{const session=G.start(template(),Date.now()-60000);session.items.forEach(it=>it.sets.forEach(s=>s.done=true));const finished=G.finish(session);finished.feedback={mood:5,effort:4,note:'Gut'};const bundle=T.pack(finished,'session',[builtin,custom],true);const plan=T.prepareImport(bundle,'template',[builtin,custom]);assert.equal(plan.record.feedback,undefined);assert.equal(plan.record.duration,undefined);assert.equal(plan.record.items[0].sets[0].done,false);const history=T.prepareImport(bundle,'session',[builtin,custom]);assert.equal(history.record.feedback.mood,5);assert.equal(history.record.items[0].sets[0].done,true);const cardio={id:'cardio',name:'Radfahren',category:'Ausdauer',date:G.localDate(),duration:3600,notes:'',items:[],cardio:{type:'Radfahren',other:'',distanceMeters:23500,elevationMeters:280}};const c=T.pack(cardio,'session',[]);assert.deepEqual(T.prepareImport(T.parse(T.code(c)),'session',[]).record.cardio,cardio.cardio);assert.throws(()=>T.prepareImport(c,'template',[]));});
test('Fehlerhafte, fremde, übergroße und manipulierte Importdaten werden zurückgewiesen',()=>{const good=T.pack(template(),'template',[builtin,custom]);for(const text of ['not json','SW1.bad!',JSON.stringify({...good,version:99}),JSON.stringify({format:'other',version:1}),'{"__proto__":{"polluted":true}}'])assert.throws(()=>T.parse(text));assert.throws(()=>T.parse('x'.repeat(T.MAX_BYTES*2+1)));for(const value of [-1,Infinity,'42',null]){const bad=G.clone(good);bad.workout.items[0].sets[0].weight=value;assert.throws(()=>T.normalize(bad));}assert.equal({}.polluted,undefined);const bad=G.clone(good);bad.workout.items[0].sets[0].reps=1.5;assert.throws(()=>T.normalize(bad));assert.throws(()=>T.normalize({...good,kind:'session',workout:{...good.workout,date:'2025-02-31',duration:10}}));});

test('Exportgrenze zählt UTF-8-Bytes, damit exportierte Dateien auch importierbar bleiben',()=>{const record=template();const it=record.items[0];it.notes='界'.repeat(10000);record.items=Array.from({length:50},()=>G.clone(it));const bundle=T.pack(record,'template',[builtin],true);assert.throws(()=>T.json(bundle),/zu groß/);assert.throws(()=>T.code(bundle),/zu groß/);});
test('Cardio- und Ballsportpläne können ohne Übungen geteilt werden; ungültige Intervalle werden abgewiesen',()=>{const plans=[{name:'Laufintervalle',category:'Ausdauer',durationMinutes:25,notes:'',items:[],cardio:{type:'Laufen',other:'',mode:'interval',distanceMeters:null,elevationMeters:null,intervals:{count:8,workSeconds:120,restSeconds:30,distanceMeters:400}}},{name:'Fußball',sport:'Fußball',category:'Ballsport',durationMinutes:90,notes:'',items:[]}];for(const p of plans){const bundle=T.pack(p,'template',[]),copy=T.prepareImport(T.parse(T.code(bundle)),'template',[]).record;assert.equal(copy.durationMinutes,p.durationMinutes);assert.deepEqual(copy.items,[]);if(p.cardio)assert.deepEqual(copy.cardio,p.cardio);else assert.equal(copy.sport,'Fußball');assert.ok(G.start(copy));}const bad=T.pack(plans[0],'template',[]);bad.workout.cardio.intervals.count=-1;assert.throws(()=>T.normalize(bad));});
