const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {JSDOM,VirtualConsole}=require(process.env.JSDOM_PATH||'jsdom');const root=path.join(__dirname,'../assets');
function setup(stored=null){const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM('<!doctype html><html lang="de"><body><div id="app"></div><dialog id="modal"></dialog><div id="toast"></div></body></html>',{url:'https://setwerk.test/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window;w.scrollTo=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};if(stored)w.localStorage.setItem('setwerk.v1',JSON.stringify(stored));for(const f of ['exercises.js','exercises-en.js','i18n.js','core.js','transfer.js','app.js']){const s=w.document.createElement('script');s.textContent=fs.readFileSync(path.join(root,f),'utf8');w.document.body.append(s);}const q=s=>w.document.querySelector(s);const click=s=>{assert.ok(q(s),'Element fehlt: '+s);q(s).click()};const input=(s,v)=>{assert.ok(q(s),'Feld fehlt: '+s);q(s).value=String(v);q(s).dispatchEvent(new w.Event('input',{bubbles:true}));q(s).dispatchEvent(new w.Event('change',{bubbles:true}));};const submit=s=>q(s).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));const read=()=>JSON.parse(w.localStorage.getItem('setwerk.v1'));return{dom,w,q,click,input,submit,read,errors};}
const act=n=>`[data-action="${n}"]`;
test('vollständiger Trainingsablauf, Erweiterung, Historie und Reload',()=>{const x=setup();const{click,input,submit,q,read,dom,w}=x;try{
 assert.equal(w.GYM_EXERCISES.length,269);assert.equal(new Set(w.GYM_EXERCISES.map(e=>e.name)).size,269);
 click(act('new-template'));input('#draft-name','Oberkörper A');click(act('pick-exercise'));input('#picker-search','Bankdrücken (Langhantel)');click('#picker-results '+act('choose-exercise'));
 assert.equal(read().draft.items[0].sets.length,3);assert.equal(read().draft.items[0].rest,120);
 click(act('pick-exercise'));input('#picker-search','Kniebeugen (Langhantel)');click('#picker-results '+act('choose-exercise'));
 assert.equal(q('[data-field="group"]'),null);input('[data-item="0"][data-set="0"][data-field="weight"]',60);submit('#editor-form');
 assert.equal(read().templates.length,1);click(act('start-template'));assert.ok(q('.focus-shell'));assert.equal(q(act('extend-final')),null);
 click(act('complete-set'));assert.ok(read().active.rest);click(act('skip-rest'));assert.match(q('.focus-main h1').textContent,/Bankdrücken/);
 click(act('early-end'));click(act('extend-early'));input('#picker-search','Laufband');click('#picker-results '+act('choose-exercise'));
 assert.equal(read().active.items.length,3);assert.ok(read().active.items[1].sets.every(s=>s.skipped));
 click(act('focus-settings'));input('[data-item="2"][data-set="0"][data-field="seconds"]',600);input('[data-item="2"][data-set="0"][data-field="distance"]',2000);
 click('[data-action="remove-set"][data-set="2"]');click('[data-action="remove-set"][data-set="1"]');click(act('close-settings'));click(act('complete-set'));assert.ok(q('.rest-overlay'));click(act('skip-rest'));assert.ok(q(act('extend-final')));
 click(act('extend-final'));input('#picker-search','Liegestütze');click('#picker-results '+act('choose-exercise'));click(act('focus-settings'));click('[data-action="remove-set"][data-set="2"]');click('[data-action="remove-set"][data-set="1"]');input('[data-item="3"][data-set="0"][data-field="reps"]',15);input('[data-item="3"][data-set="0"][data-field="rpe"]',8);click(act('close-settings'));click(act('complete-set'));click(act('skip-rest'));click(act('save-active'));click(act('skip-feedback'));
 assert.equal(read().active,null);assert.equal(read().sessions.length,1);assert.equal(read().sessions[0].items.length,3);assert.equal(read().sessions[0].items[2].sets[0].rpe,8);assert.equal(read().templates[0].items[1].sets[0].skipped,false);
 click(act('close-modal'));click('[data-action="nav-exercises"]');input('#exercise-search','Bankdrücken (Langhantel)');click('#exercise-results '+act('exercise'));assert.match(q('#modal').textContent,/60 kg/);click(act('close-modal'));
 const restored=setup(read());assert.match(restored.q('#app').textContent,/Oberkörper A/);assert.equal(restored.read().sessions.length,1);restored.dom.window.close();assert.deepEqual(x.errors,[]);
}finally{dom.window.close();}});
test('Manuelle Sporteinheit, bearbeiten, Kalenderfarben und Löschen',()=>{const x=setup();const{click,input,submit,q,read,dom}=x;try{click(act('manual-new'));input('#draft-name','Fußballtraining');input('[data-draft="category"]','Ballsport');input('[data-draft="durationMinutes"]',90);submit('#editor-form');assert.equal(read().sessions[0].duration,5400);assert.ok(q('.dot-ballsport'));click(act('session'));click(act('edit-session'));input('#draft-name','Fußballtraining Team');input('[data-draft="durationMinutes"]',100);submit('#editor-form');assert.equal(read().sessions.length,1);assert.equal(read().sessions[0].duration,6000);click(act('session'));click(act('delete-session'));click(act('confirm-delete-session'));assert.equal(read().sessions.length,0);assert.deepEqual(x.errors,[]);}finally{dom.window.close();}});
test('Eigene Übungen, Entwurfwiederaufnahme, Ziele und sichere Texte',()=>{const x=setup();const{click,input,submit,q,read,dom}=x;try{click(act('nav-exercises'));click(act('custom-exercise'));input('[name="name"]','<img src=x onerror=alert(1)>');input('[name="equipment"]','Eigengewicht');input('[name="instructions"]','Ruhige Ausführung');submit('#custom-form');assert.equal(read().customExercises.length,1);assert.equal(q('#app img'),null);click('[data-action="nav"][data-route="home"]');click(act('new-template'));input('#draft-name','Entwurf');click('[data-action="nav"][data-route="templates"]');click('[data-action="nav"][data-route="home"]');click(act('resume-draft'));assert.equal(q('#draft-name').value,'Entwurf');click('[data-action="nav"][data-route="home"]');click(act('goals'));input('[name="weekly"]',4);submit('#goals-form');assert.equal(read().goals.weekly,4);assert.deepEqual(x.errors,[]);}finally{dom.window.close();}});
test('Aktives Workout und Pausen-Endzeit überleben Reload',()=>{const x=setup();try{const G=x.w.GymCore,ex=x.w.GYM_EXERCISES[0],s=G.fresh();s.active=G.start({name:'Reload',items:[G.item(ex)]});G.complete(s.active);const y=setup(s);assert.ok(y.q('.focus-shell'));assert.ok(y.q('.rest-overlay'));assert.equal(y.read().active.rest.until,s.active.rest.until);y.dom.window.close();}finally{x.dom.window.close();}});
test('Spontantraining, direkte Eingaben, Übungswechsel und Feedback im Verlauf',()=>{const x=setup();const{w,click,input,submit,q,read,dom}=x;try{
 click(act('start-select'));click(act('start-spontaneous'));assert.equal(read().active.items.length,0);assert.equal(read().templates.length,0);assert.match(q('.focus-main').textContent,/Die Einheit läuft/);click(act('extend-final'));input('#picker-search','Bankdrücken (Langhantel)');click('#picker-results '+act('choose-exercise'));
 assert.equal(q(act('complete-set')).textContent,'Nächster Satz');assert.equal(q('.focus-top [data-action="focus-settings"]'),null);
 click('[data-action="edit-value"][data-field="reps"]');input('#quick-value',12);click('[name="remaining"]');submit('#value-form');assert.deepEqual(read().active.items[0].sets.map(s=>s.reps),[12,12,12]);
 click('[data-action="edit-value"][data-field="weight"]');input('#quick-value',62.5);submit('#value-form');assert.deepEqual(read().active.items[0].sets.map(s=>s.weight),[62.5,0,0]);assert.ok(q('.motion-value'));
 click(act('complete-set'));click(act('skip-rest'));assert.ok(q('.motion-set'));click('.focus-exercise-title '+act('replace-exercise'));input('#picker-search','Liegestütze');click('#picker-results '+act('choose-exercise'));
 const a=read().active;assert.equal(a.items.length,2);assert.equal(a.items[0].sets.length,1);assert.equal(a.items[0].sets[0].weight,62.5);assert.equal(a.items[1].sets.length,2);assert.equal(a.items[1].sets[0].weight,0);assert.ok(q('.motion-exercise'));
 click(act('complete-set'));click(act('skip-rest'));click(act('early-end'));click(act('save-active'));assert.ok(q('#feedback-form'));const endedAt=read().active.finishedAt;
 click('[name="mood"][value="4"]');click('[name="effort"][value="3"]');input('[name="feedbackNote"]','Gut & Kraft <script>');submit('#feedback-form');assert.equal(read().active,null);assert.equal(read().sessions[0].endedAt,endedAt);assert.deepEqual(read().sessions[0].feedback,{mood:4,effort:3,note:'Gut & Kraft <script>'});
 click(act('session'));assert.match(q('.feedback-summary').textContent,/Gut & Kraft <script>/);assert.equal(q('#modal script'),null);click(act('edit-feedback'));click('[name="mood"][value="5"]');submit('#feedback-form');assert.equal(read().sessions[0].feedback.mood,5);assert.deepEqual(x.errors,[]);
 }finally{dom.window.close();}});
test('Englisch in Navigation, Katalog, Eingaben und Training; eigene Texte bleiben erhalten',()=>{const x=setup();const{w,click,input,submit,q,read,dom}=x;try{
 click(act('toggle-language'));assert.equal(w.document.documentElement.lang,'en');assert.match(q('#app').textContent,/Start workout/);assert.doesNotMatch(q('#app').textContent,/Übersicht|Vorlagen|Kalender|Einheiten|gespeichert/);
 click(act('nav-exercises'));input('#exercise-search','bench press');assert.match(q('#exercise-results').textContent,/Bench press/i);click('#exercise-results '+act('exercise'));assert.match(q('#modal').textContent,/BEST SET/);assert.doesNotMatch(q('#modal').textContent,/Wiederholungen|Gewicht|Anleitung|Ausführung/);click(act('close-modal'));
 click('[data-action="nav"][data-route="home"]');click(act('new-template'));input('#draft-name','Kraft Training Gut');input('[data-draft="notes"]','Sehr gut · Gewicht unverändert');assert.equal(q('[data-draft="category"]').value,'Kraft');assert.equal(q('[data-draft="category"] option').textContent,'Strength');
 click(act('pick-exercise'));input('#picker-search','Bankdrücken (Langhantel)');click('#picker-results '+act('choose-exercise'));assert.match(q('.exercise-edit h3').textContent,/Bench press/i);assert.equal(q('[data-field="group"]'),null);submit('#editor-form');assert.match(q('.template-card h2').textContent,/Kraft Training Gut/);assert.equal(read().templates[0].notes,'Sehr gut · Gewicht unverändert');click(act('start-template'));assert.equal(q(act('complete-set')).textContent,'Next set');
 click('[data-action="edit-value"][data-field="weight"]');assert.match(q('#modal').textContent,/Edit weight/);input('#quick-value',40);submit('#value-form');click(act('complete-set'));assert.match(q('.rest-overlay').textContent,/Your rest/);click(act('skip-rest'));click(act('early-end'));click(act('save-active'));assert.match(q('#modal').textContent,/How do you feel right now/);click(act('skip-feedback'));click(act('session'));assert.match(q('#modal').textContent,/Sehr gut · Gewicht unverändert/);assert.doesNotMatch(q('#app').innerHTML+q('#modal').innerHTML,/[\uE000\uE001]/);
 const y=setup(read());assert.equal(y.w.document.documentElement.lang,'en');assert.match(y.q('#app').textContent,/Kraft Training Gut/);y.dom.window.close();assert.deepEqual(x.errors,[]);
 }finally{dom.window.close();}});
test('Feedback nach Neustart fortsetzen oder zum Training zurückkehren',()=>{const x=setup();try{const G=x.w.GymCore,s=G.fresh();s.active=G.start({name:'Test',items:[G.item(x.w.GYM_EXERCISES[0],2,0)]});G.complete(s.active);s.active.feedbackStage=true;s.active.finishedAt=Date.now();const y=setup(s);assert.ok(y.q('#feedback-form'));assert.equal(y.read().active.finishedAt,s.active.finishedAt);y.click(act('close-modal'));assert.equal(y.read().active.feedbackStage,undefined);assert.equal(y.read().active.finishedAt,undefined);assert.ok(y.q(act('complete-set')));y.dom.window.close();}finally{x.dom.window.close();}});
test('Cardio im Kalender fragt nur Aktivität und relevante Werte ab und erhält sie beim Bearbeiten',()=>{const x=setup();const{click,input,submit,q,read,dom}=x;try{
 click(act('nav-calendar'));click(act('manual-new'));input('[data-draft="category"]','Ausdauer');assert.ok(q('.cardio-form'));assert.equal(q('[data-field="weight"]'),null);assert.equal(q(act('pick-exercise')),null);assert.equal(q('#draft-name'),null);assert.equal(q('#manual-template'),null);assert.equal(q('select[data-cardio="type"]').options.length,7);
 input('[data-cardio="type"]','Radfahren');input('[data-draft="durationMinutes"]',75);input('[data-cardio="distanceKm"]',25.75);input('[data-cardio="elevationM"]',320);submit('#editor-form');let s=read().sessions[0];assert.equal(s.duration,4500);assert.equal(s.name,'Radfahren');assert.equal(s.items.length,0);assert.deepEqual(s.cardio,{type:'Radfahren',other:'',distanceMeters:25750,elevationMeters:320});assert.ok(q('.dot-ausdauer'));click(act('session'));assert.match(q('#modal').textContent,/25,75 km/);assert.doesNotMatch(q('#modal').textContent,/SÄTZE/);
 click(act('edit-session'));assert.equal(q('[data-cardio="distanceKm"]').value,'25.75');input('[data-cardio="type"]','Sonstige');assert.ok(q('[data-cardio="other"]'));input('[data-cardio="other"]','Wandern');input('[data-cardio="elevationM"]','');submit('#editor-form');s=read().sessions[0];assert.equal(read().sessions.length,1);assert.equal(s.name,'Wandern');assert.equal(s.cardio.elevationMeters,null);
 click(act('session'));click(act('edit-session'));input('[data-cardio="type"]','Seilspringen');assert.equal(q('[data-cardio="distanceKm"]'),null);submit('#editor-form');assert.equal(read().sessions[0].cardio.distanceMeters,null);assert.equal(read().sessions[0].name,'Seilspringen');assert.deepEqual(x.errors,[]);
 }finally{dom.window.close();}});
test('Cardio-Eingaben validieren, Kategorie wechseln und Entwurf nach Reload fortsetzen',()=>{const x=setup();const{click,input,submit,q,read,dom}=x;try{click(act('manual-new'));input('[data-draft="category"]','Ausdauer');input('[data-cardio="type"]','Sonstige');submit('#editor-form');assert.equal(read().sessions.length,0);assert.match(q('#toast').textContent,/Textfeld/);input('[data-cardio="other"]','Wandern');input('[data-cardio="distanceKm"]',8.2);input('[data-cardio="elevationM"]',-1);submit('#editor-form');assert.equal(read().sessions.length,0);input('[data-cardio="elevationM"]',200);input('[data-draft="category"]','Kraft');assert.ok(q(act('pick-exercise')));input('[data-draft="category"]','Ausdauer');assert.equal(q('[data-cardio="other"]').value,'Wandern');const y=setup(read());y.click(act('resume-draft'));assert.equal(y.q('[data-cardio="distanceKm"]').value,'8.2');y.submit('#editor-form');assert.equal(y.read().sessions.length,1);y.dom.window.close();assert.deepEqual(x.errors,[]);}finally{dom.window.close();}});
test('Teilen und Importvorschau übernehmen Pläne ohne fremde Einheiten zum Verlauf zu zählen',()=>{const x=setup();const{w,click,input,submit,q,read,dom}=x;try{click(act('manual-new'));input('#draft-name','Plan von Freunden <img src=x>');click(act('pick-exercise'));input('#picker-search','Bankdrücken (Langhantel)');click('#picker-results '+act('choose-exercise'));input('[data-draft="notes"]','Persönliche Notiz');submit('#editor-form');click(act('session'));click(act('export-session'));click(act('export-code'));const code=q('#workout-code').value;assert.equal(w.SetwerkTransfer.parse(code).workout.notes,'');click('#share-personal');assert.equal(w.SetwerkTransfer.parse(q('#workout-code').value).workout.notes,'Persönliche Notiz');click(act('close-modal'));click('[data-action="nav"][data-route="templates"]');click(act('import-workout'));input('#workout-import-code',code);click(act('preview-import'));assert.equal(read().templates.length,0);assert.match(q('#import-preview').textContent,/Plan von Freunden/);assert.equal(q('#import-preview img'),null);click('[data-action="confirm-import"][data-target="template"]');assert.equal(read().templates.length,1);assert.equal(read().sessions.length,1);assert.equal(read().templates[0].items[0].sets[0].done,false);assert.notEqual(read().templates[0].id,read().sessions[0].id);click(act('export-template'));click(act('export-code'));assert.equal(w.SetwerkTransfer.parse(q('#workout-code').value).kind,'template');click(act('close-modal'));click('[data-action="nav"][data-route="templates"]');click(act('import-workout'));input('#workout-import-code','SW1.not-valid!');click(act('preview-import'));assert.ok(q('#import-error').textContent);assert.equal(q(act('confirm-import')),null);assert.equal(read().templates.length,1);assert.deepEqual(x.errors,[]);}finally{dom.window.close();}});
test('Englische Cardio- und Importoberfläche',()=>{const x=setup();const{click,input,q,dom}=x;try{click(act('toggle-language'));click(act('manual-new'));input('[data-draft="category"]','Ausdauer');assert.match(q('#app').textContent,/Cardio activity/);assert.match(q('#app').textContent,/Elevation gain \(optional\)/);input('[data-cardio="type"]','Sonstige');assert.match(q('#app').textContent,/Which activity/);click('[data-action="nav"][data-route="calendar"]');click('[data-action="nav"][data-route="templates"]');click(act('import-workout'));assert.match(q('#modal').textContent,/Choose file/);input('#workout-import-code','bad');click(act('preview-import'));assert.equal(q('#import-error').textContent,'Invalid workout file or code.');assert.doesNotMatch(q('#modal').innerHTML,/[\uE000\uE001]/);assert.deepEqual(x.errors,[]);}finally{dom.window.close();}});
test('Datei-Auswahl importiert Cardio lokal, Download erzeugt gültiges JSON und privates Feedback bleibt optional',async()=>{const x=setup();const{w,click,input,submit,q,read,dom}=x;try{
 click(act('manual-new'));input('[data-draft="category"]','Ausdauer');input('[data-draft="durationMinutes"]',30.5);input('[data-cardio="distanceKm"]',5);submit('#editor-form');click(act('session'));click(act('edit-session'));assert.equal(q('[data-draft="durationMinutes"]').value,'30.5');submit('#editor-form');click(act('session'));click(act('export-session'));
 let exportedFile,downloadName;w.URL.createObjectURL=file=>{exportedFile=file;return'blob:test'};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){downloadName=this.download;};click(act('export-file'));assert.match(downloadName,/\.setwerk\.json$/);assert.ok(exportedFile instanceof w.File);click(act('close-modal'));click('[data-action="nav"][data-route="templates"]');click(act('import-workout'));const fileInput=q('#workout-import-file');Object.defineProperty(fileInput,'files',{value:[exportedFile]});fileInput.dispatchEvent(new w.Event('change',{bubbles:true}));for(let i=0;i<20&&!q('[data-action="confirm-import"]');i++)await new Promise(r=>setTimeout(r,10));assert.ok(q('[data-action="confirm-import"][data-target="session"]'));assert.equal(q('[data-action="confirm-import"][data-target="template"]'),null);click('[data-action="confirm-import"][data-target="session"]');assert.equal(read().sessions.length,2);assert.notEqual(read().sessions[0].id,read().sessions[1].id);assert.deepEqual(read().sessions[0].cardio,read().sessions[1].cardio);assert.equal(read().sessions[1].duration,1830);assert.deepEqual(x.errors,[]);
 }finally{dom.window.close();}});



test('language slider toggles directly, persists, and removes the previous language field',()=>{
 const x=setup();try{
  assert.equal(x.q('.language-switch'),null);assert.equal(x.q('[data-action=language]'),null);assert.equal(x.q('.app-topbar [role=switch]').getAttribute('aria-checked'),'false');
  x.click(act('toggle-language'));assert.equal(x.read().language,'en');assert.equal(x.q('[role=switch]').getAttribute('aria-checked'),'true');assert.equal(x.q('#modal').open,false);
  x.click(act('toggle-language'));assert.equal(x.read().language,'de');assert.equal(x.w.document.documentElement.lang,'de');assert.deepEqual(x.errors,[]);
 }finally{x.dom.window.close();}
});
test('Kalender ohne Import, Höhenmeter nur für passende Aktivitäten und ohne versteckte Werte',()=>{const x=setup();const{click,input,submit,q,read,dom}=x;try{
 click(act('nav-calendar'));assert.equal(q(act('import-workout')),null);click(act('manual-new'));input('[data-draft="category"]','Ausdauer');input('[data-cardio="type"]','Radfahren');input('[data-cardio="distanceKm"]',12);input('[data-cardio="elevationM"]',400);input('[data-cardio="type"]','Schwimmen');assert.equal(q('[data-cardio="elevationM"]'),null);input('[data-draft="notes"]','Becken 25 m');submit('#editor-form');assert.equal(read().sessions[0].cardio.elevationMeters,null);assert.equal(read().sessions[0].notes,'Becken 25 m');click(act('session'));assert.doesNotMatch(q('#modal').textContent,/HÖHENMETER/);click(act('edit-session'));assert.equal(q('[data-cardio="elevationM"]'),null);assert.equal(q('[data-draft="notes"]').value,'Becken 25 m');assert.deepEqual(x.errors,[]);
 }finally{dom.window.close();}});
test('Cardio-Intervallvorlage bleibt über Reload erhalten und startet ohne Kraftübungen',()=>{const x=setup();const{click,input,submit,q,read,dom}=x;try{
 click(act('new-template'));input('#draft-name','Schwimmintervalle');input('[data-draft="category"]','Ausdauer');assert.equal(q(act('pick-exercise')),null);input('[data-cardio="mode"]','interval');input('[data-cardio="type"]','Schwimmen');assert.equal(q('[data-cardio="elevationM"]'),null);input('[data-cardio="count"]',8);input('[data-cardio="workSeconds"]',120);input('[data-cardio="restSeconds"]',30);input('[data-cardio="intervalDistanceM"]',100);input('[data-draft="notes"]','Technik beachten');assert.equal(Number(q('[data-draft="durationMinutes"]').value),19.5);
 const y=setup(read());y.click(act('resume-draft'));assert.equal(y.q('[data-cardio="count"]').value,'8');y.submit('#editor-form');let t=y.read().templates[0];assert.equal(t.items.length,0);assert.equal(t.cardio.intervals.distanceMeters,100);assert.equal(t.durationMinutes,19.5);assert.doesNotMatch(y.q('.template-card').textContent,/Übungen|Sätze/);y.click(act('start-template'));assert.ok(y.q('#activity-clock'));assert.equal(y.q(act('complete-set')),null);assert.equal(y.read().sessions.length,0);assert.equal(y.read().active.cardio.intervals.count,8);
 const z=setup(y.read());assert.ok(z.q('#activity-clock'));z.click(act('activity-finish'));z.input('[name="minutes"]',24);z.input('[name="distanceKm"]',0.8);z.submit('#activity-finish-form');z.click(act('skip-feedback'));const session=z.read().sessions[0];assert.equal(session.duration,1440);assert.equal(session.cardio.distanceMeters,800);assert.equal(session.items.length,0);assert.equal(session.notes,'Technik beachten');assert.equal(z.read().templates[0].cardio.distanceMeters,null);z.dom.window.close();y.dom.window.close();assert.deepEqual(x.errors,[]);
 }finally{dom.window.close();}});
test('Ballsportvorlage mit Sport, Dauer und Notizen startet und beendet sich ohne Sätze',()=>{const x=setup();const{click,input,submit,q,read,dom}=x;try{
 click(act('new-template'));input('[data-draft="category"]','Ballsport');assert.equal(q(act('pick-exercise')),null);input('#draft-name','Volleyball');input('[data-draft="durationMinutes"]',90);input('[data-draft="notes"]','Training mit Freunden');submit('#editor-form');let t=read().templates[0];assert.equal(t.sport,'Volleyball');assert.equal(t.items.length,0);assert.equal(t.durationMinutes,90);click(act('edit-template'));assert.equal(q('[data-draft="durationMinutes"]').value,'90');submit('#editor-form');click(act('start-template'));assert.ok(q('#activity-clock'));click(act('activity-finish'));assert.equal(q('[name="distanceKm"]'),null);input('[name="minutes"]',85);submit('#activity-finish-form');click(act('skip-feedback'));assert.equal(read().sessions[0].duration,5100);assert.equal(read().sessions[0].sport,'Volleyball');click(act('session'));assert.doesNotMatch(q('#modal').textContent,/SÄTZE/);click(act('edit-session'));assert.equal(q(act('pick-exercise')),null);assert.equal(q('[data-draft="notes"]').value,'Training mit Freunden');assert.deepEqual(x.errors,[]);
 }finally{dom.window.close();}});
test('Sonstige Cardio-Form und Aktivität validieren, Kategorien behalten Entwurf und teilen neue Pläne',()=>{const x=setup();const{click,input,submit,q,read,dom,w}=x;try{
 click(act('new-template'));input('#draft-name','Eigener Cardio-Plan');click(act('pick-exercise'));click('#picker-results '+act('choose-exercise'));input('[data-draft="category"]','Ausdauer');input('[data-cardio="mode"]','other');input('[data-cardio="type"]','Sonstige');submit('#editor-form');assert.equal(read().templates.length,0);input('[data-cardio="modeName"]','Fahrtspiel <img src=x>');input('[data-cardio="other"]','Wandern');input('[data-draft="category"]','Kraft-Ausdauer');assert.ok(q(act('pick-exercise')));assert.equal(read().draft.items.length,1);input('[data-draft="category"]','Ausdauer');assert.equal(q('[data-cardio="modeName"]').value,'Fahrtspiel <img src=x>');submit('#editor-form');assert.equal(read().templates[0].items.length,0);assert.equal(read().templates[0].cardio.modeName,'Fahrtspiel <img src=x>');assert.equal(q('.template-card img'),null);
 click(act('export-template'));click(act('export-code'));const code=q('#workout-code').value;assert.equal(w.SetwerkTransfer.parse(code).workout.cardio.mode,'other');click(act('close-modal'));click(act('import-workout'));input('#workout-import-code',code);click(act('preview-import'));assert.equal(q('#import-preview img'),null);click('[data-action="confirm-import"][data-target="template"]');assert.equal(read().templates.length,2);assert.equal(read().templates[1].cardio.other,'Wandern');assert.deepEqual(x.errors,[]);
 }finally{dom.window.close();}});
test('Neue Cardio- und Ballsportoptionen sind auch auf Englisch vollständig bedienbar',()=>{const x=setup();const{click,input,q,dom}=x;try{
 click(act('toggle-language'));click(act('new-template'));input('[data-draft="category"]','Ausdauer');input('[data-cardio="mode"]','interval');assert.match(q('#app').textContent,/Number of intervals/);assert.match(q('#app').textContent,/Rest between intervals/);assert.doesNotMatch(q('#app').textContent,/Trainingsform|Belastung|zwischen Intervallen/);input('[data-cardio="mode"]','other');assert.match(q('#app').textContent,/Training style name/);input('[data-draft="category"]','Ballsport');assert.match(q('#app').textContent,/Sport/);assert.equal(q(act('pick-exercise')),null);assert.deepEqual(x.errors,[]);
 }finally{dom.window.close();}});
test('Bearbeiten alter Sporteinheiten erhält vorhandene Übungshistorie trotz ausgeblendetem Editor',()=>{for(const category of ['Ausdauer','Ballsport']){const x=setup();try{const G=x.w.GymCore,state=G.fresh(),item=G.item(x.w.GYM_EXERCISES[0],1);item.sets[0].done=true;state.sessions=[{id:'legacy',name:'Sport',category,date:G.localDate(),duration:3600,startedAt:1,endedAt:2,notes:'Alt',items:[item],...(category==='Ausdauer'?{cardio:{type:'Radfahren',other:'',distanceMeters:10000,elevationMeters:30}}:{})}];const y=setup(state);try{y.click(act('session'));y.click(act('edit-session'));assert.equal(y.q(act('pick-exercise')),null);y.input('[data-draft="notes"]','Überarbeitet');y.submit('#editor-form');assert.equal(y.read().sessions[0].items[0].exerciseId,item.exerciseId);assert.equal(y.read().sessions[0].items[0].sets[0].done,true);assert.equal(y.read().sessions[0].notes,'Überarbeitet');assert.deepEqual(y.errors,[]);}finally{y.dom.window.close();}}finally{x.dom.window.close();}}});
