import json
from pathlib import Path
# Eigenständig formulierte Hinweise nach Bewegungsmuster; keine externen Medien.
groups = [
('Brust','press','reps', [
('Bankdrücken (Langhantel)','Langhantel'),('Schrägbankdrücken (Langhantel)','Langhantel'),('Negativbankdrücken (Langhantel)','Langhantel'),('Bankdrücken (Kurzhanteln)','Kurzhanteln'),('Schrägbankdrücken (Kurzhanteln)','Kurzhanteln'),('Negativbankdrücken (Kurzhanteln)','Kurzhanteln'),('Brustpresse','Maschine'),('Schrägbrustpresse','Maschine'),('Bankdrücken (Smith-Maschine)','Smith-Maschine'),('Schrägbankdrücken (Smith-Maschine)','Smith-Maschine'),('Floor Press (Kurzhanteln)','Kurzhanteln'),('Floor Press (Langhantel)','Langhantel'),('Squeeze Press','Kurzhanteln'),('Brustdrücken (Kabelzug)','Kabelzug')]),
('Brust','fly','reps', [('Butterfly','Maschine'),('Butterfly (Kabelzug)','Kabelzug'),('Fliegende (Kurzhanteln)','Kurzhanteln'),('Fliegende auf Schrägbank','Kurzhanteln'),('Cable Crossover von oben','Kabelzug'),('Cable Crossover von unten','Kabelzug')]),
('Brust','pushup','reps', [('Liegestütze','Eigengewicht'),('Liegestütze mit erhöhten Händen','Eigengewicht'),('Liegestütze mit erhöhten Füßen','Eigengewicht'),('Enge Liegestütze','Eigengewicht'),('Breite Liegestütze','Eigengewicht'),('Liegestütze auf Knien','Eigengewicht'),('Ring-Liegestütze','Ringe'),('TRX-Brustdrücken','TRX')]),
('Brust','dip','reps',[('Dips (Brustfokus)','Parallelbarren'),('Dips mit Unterstützung','Maschine')]),
('Rücken','row','reps', [('Langhantelrudern','Langhantel'),('Langhantelrudern im Untergriff','Langhantel'),('Pendlay Row','Langhantel'),('Kurzhantelrudern einarmig','Kurzhanteln'),('Kurzhantelrudern beidarmig','Kurzhanteln'),('Brustgestütztes Rudern (Kurzhanteln)','Kurzhanteln'),('T-Bar-Rudern','Landmine'),('T-Bar-Rudern brustgestützt','Maschine'),('Kabelrudern eng','Kabelzug'),('Kabelrudern breit','Kabelzug'),('Kabelrudern einarmig','Kabelzug'),('Rudermaschine sitzend','Maschine'),('High Row','Maschine'),('Rudern an der Smith-Maschine','Smith-Maschine'),('Rudern mit Widerstandsband','Widerstandsband'),('TRX-Rudern','TRX'),('Inverted Row','Eigengewicht'),('Ring-Rudern','Ringe'),('Meadows Row','Landmine')]),
('Rücken','pulldown','reps',[('Latzug breit','Kabelzug'),('Latzug eng','Kabelzug'),('Latzug im Untergriff','Kabelzug'),('Latzug einarmig','Kabelzug'),('Latzug neutraler Griff','Kabelzug'),('Klimmzüge im Obergriff','Klimmzugstange'),('Klimmzüge im Untergriff','Klimmzugstange'),('Klimmzüge neutraler Griff','Klimmzugstange'),('Klimmzüge mit Unterstützung','Maschine'),('Klimmzüge mit Widerstandsband','Widerstandsband'),('Negative Klimmzüge','Klimmzugstange'),('Scapular Pull-ups','Klimmzugstange')]),
('Rücken','pullover','reps',[('Überzüge (Kurzhantel)','Kurzhanteln'),('Überzüge (Kabelzug)','Kabelzug'),('Überzugmaschine','Maschine')]),
('Rücken','backextension','reps',[('Rückenstrecken auf der 45°-Bank','Bank'),('Rückenstreckmaschine','Maschine'),('Superman','Eigengewicht'),('Reverse Hyperextension','Maschine')]),
('Schultern','overhead','reps',[('Schulterdrücken (Kurzhanteln)','Kurzhanteln'),('Schulterdrücken sitzend (Langhantel)','Langhantel'),('Military Press','Langhantel'),('Arnold Press','Kurzhanteln'),('Schulterpresse','Maschine'),('Schulterdrücken (Smith-Maschine)','Smith-Maschine'),('Landmine Press','Landmine'),('Schulterdrücken einarmig (Kettlebell)','Kettlebell'),('Pike Push-ups','Eigengewicht'),('Z-Press','Langhantel')]),
('Schultern','raise','reps',[('Seitheben (Kurzhanteln)','Kurzhanteln'),('Seitheben (Kabelzug)','Kabelzug'),('Seithebemaschine','Maschine'),('Seitheben sitzend','Kurzhanteln'),('Frontheben (Kurzhanteln)','Kurzhanteln'),('Frontheben (Kabelzug)','Kabelzug'),('Frontheben mit Gewichtsscheibe','Gewichtsscheibe'),('Y-Raises auf der Schrägbank','Kurzhanteln')]),
('Schultern','reversefly','reps',[('Reverse Butterfly','Maschine'),('Reverse Fly (Kurzhanteln)','Kurzhanteln'),('Reverse Fly (Kabelzug)','Kabelzug'),('Face Pulls','Kabelzug'),('Band Pull-Aparts','Widerstandsband'),('Außenrotation (Kabelzug)','Kabelzug'),('Außenrotation (Widerstandsband)','Widerstandsband')]),
('Schultern','shrug','reps',[('Shrugs (Kurzhanteln)','Kurzhanteln'),('Shrugs (Langhantel)','Langhantel'),('Shrugs (Smith-Maschine)','Smith-Maschine')]),
('Bizeps','curl','reps',[('Bizepscurls (Langhantel)','Langhantel'),('Bizepscurls (SZ-Stange)','SZ-Stange'),('Bizepscurls (Kurzhanteln)','Kurzhanteln'),('Alternierende Bizepscurls','Kurzhanteln'),('Hammercurls','Kurzhanteln'),('Cross-Body Hammercurls','Kurzhanteln'),('Schrägbankcurls','Kurzhanteln'),('Konzentrationscurls','Kurzhanteln'),('Scottcurls (SZ-Stange)','SZ-Stange'),('Scottcurls (Kurzhantel)','Kurzhanteln'),('Bizepsmaschine','Maschine'),('Kabelcurls mit gerader Stange','Kabelzug'),('Kabelcurls mit Seil','Kabelzug'),('Kabelcurls einarmig','Kabelzug'),('Bayesian Curls','Kabelzug'),('Spider Curls','Kurzhanteln'),('Reverse Curls (SZ-Stange)','SZ-Stange'),('Zottman Curls','Kurzhanteln'),('Bizepscurls mit Widerstandsband','Widerstandsband'),('TRX-Bizepscurls','TRX')]),
('Trizeps','triceps','reps',[('Trizepsdrücken mit Seil','Kabelzug'),('Trizepsdrücken mit gerader Stange','Kabelzug'),('Trizepsdrücken einarmig','Kabelzug'),('Trizepsdrücken im Untergriff','Kabelzug'),('Überkopf-Trizepsstrecken (Seil)','Kabelzug'),('Überkopf-Trizepsstrecken (Kurzhantel)','Kurzhanteln'),('French Press (SZ-Stange)','SZ-Stange'),('Skull Crushers (Kurzhanteln)','Kurzhanteln'),('Trizeps-Kickbacks (Kurzhantel)','Kurzhanteln'),('Trizeps-Kickbacks (Kabelzug)','Kabelzug'),('Trizepsmaschine','Maschine'),('Trizepsstrecken mit Widerstandsband','Widerstandsband'),('TRX-Trizepsstrecken','TRX')]),
('Trizeps','press','reps',[('Enges Bankdrücken','Langhantel'),('Enges Bankdrücken (Smith-Maschine)','Smith-Maschine')]),
('Trizeps','dip','reps',[('Dips (Trizepsfokus)','Parallelbarren')]),
('Unterarme','wrist','reps',[('Handgelenkcurls (Kurzhantel)','Kurzhanteln'),('Reverse Handgelenkcurls','Kurzhanteln'),('Handgelenkcurls (Langhantel)','Langhantel'),('Handgelenkrollen','Wrist Roller'),('Grifftrainer','Grifftrainer')]),
('Unterarme','hold','time',[('Dead Hang','Klimmzugstange'),('Gewichtsscheiben halten','Gewichtsscheibe'),('Farmer Hold','Kurzhanteln')]),
('Beine','squat','reps',[('Kniebeugen (Langhantel)','Langhantel'),('Frontkniebeugen','Langhantel'),('Goblet Squats','Kettlebell'),('Kniebeugen mit Kurzhanteln','Kurzhanteln'),('Kniebeugen (Smith-Maschine)','Smith-Maschine'),('Hackenschmidt-Kniebeugen','Maschine'),('Pendulum Squat','Maschine'),('Belt Squat','Maschine'),('Kniebeugen mit Eigengewicht','Eigengewicht'),('Sumo-Kniebeugen','Kurzhanteln'),('Box Squats','Langhantel'),('Fersen erhöhte Kniebeugen','Kurzhanteln'),('Landmine Squats','Landmine'),('Pistol Squats mit Unterstützung','Eigengewicht')]),
('Beine','legpress','reps',[('Beinpresse 45°','Maschine'),('Beinpresse horizontal','Maschine'),('Beinpresse einbeinig','Maschine')]),
('Beine','lunge','reps',[('Ausfallschritte vorwärts','Eigengewicht'),('Ausfallschritte rückwärts','Eigengewicht'),('Gehende Ausfallschritte','Kurzhanteln'),('Ausfallschritte (Langhantel)','Langhantel'),('Bulgarian Split Squats','Kurzhanteln'),('Split Squats','Kurzhanteln'),('Seitliche Ausfallschritte','Eigengewicht'),('Step-ups','Kurzhanteln'),('Reverse Lunges (Smith-Maschine)','Smith-Maschine'),('Cossack Squats','Eigengewicht')]),
('Beine','legextension','reps',[('Beinstrecker','Maschine'),('Beinstrecker einbeinig','Maschine'),('Reverse Nordic Curl','Eigengewicht')]),
('Beinbeuger','hinge','reps',[('Rumänisches Kreuzheben (Langhantel)','Langhantel'),('Rumänisches Kreuzheben (Kurzhanteln)','Kurzhanteln'),('Einbeiniges rumänisches Kreuzheben','Kurzhanteln'),('Good Mornings','Langhantel'),('Kreuzheben','Langhantel'),('Sumo-Kreuzheben','Langhantel'),('Trap-Bar-Kreuzheben','Trap Bar'),('Kreuzheben (Kettlebell)','Kettlebell'),('Kabel-Pull-Through','Kabelzug')]),
('Beinbeuger','legcurl','reps',[('Beinbeuger liegend','Maschine'),('Beinbeuger sitzend','Maschine'),('Beinbeuger stehend','Maschine'),('Beinbeuger einbeinig','Maschine'),('Nordic Curls','Eigengewicht'),('Beinbeuger mit Gymnastikball','Gymnastikball'),('Sliding Leg Curls','Slider')]),
('Gesäß','bridge','reps',[('Hip Thrust (Langhantel)','Langhantel'),('Hip Thrust (Maschine)','Maschine'),('Hip Thrust (Smith-Maschine)','Smith-Maschine'),('Glute Bridge','Eigengewicht'),('Einbeinige Glute Bridge','Eigengewicht'),('Hip Thrust einbeinig','Eigengewicht'),('Frog Pumps','Eigengewicht')]),
('Gesäß','hip','reps',[('Kickbacks (Kabelzug)','Kabelzug'),('Glute-Kickback-Maschine','Maschine'),('Donkey Kicks','Eigengewicht'),('Fire Hydrants','Eigengewicht'),('Abduktorenmaschine','Maschine'),('Hüftabduktion (Kabelzug)','Kabelzug'),('Seitliches Beinheben','Eigengewicht'),('Lateral Band Walks','Widerstandsband'),('Clamshells','Widerstandsband'),('Adduktorenmaschine','Maschine'),('Hüftadduktion (Kabelzug)','Kabelzug')]),
('Waden','calf','reps',[('Wadenheben stehend','Maschine'),('Wadenheben sitzend','Maschine'),('Wadenheben an der Beinpresse','Maschine'),('Wadenheben einbeinig','Eigengewicht'),('Wadenheben (Kurzhanteln)','Kurzhanteln'),('Wadenheben (Smith-Maschine)','Smith-Maschine'),('Tibialis Raises','Eigengewicht')]),
('Core','crunch','reps',[('Crunches','Eigengewicht'),('Kabel-Crunches','Kabelzug'),('Bauchmaschine','Maschine'),('Reverse Crunches','Eigengewicht'),('Bicycle Crunches','Eigengewicht'),('Sit-ups','Eigengewicht'),('Sit-ups auf Schrägbank','Bank'),('Russian Twists','Gewichtsscheibe'),('Beinheben liegend','Eigengewicht'),('Beinheben hängend','Klimmzugstange'),('Knieheben hängend','Klimmzugstange'),('Knieheben am Dipständer','Parallelbarren'),('Dead Bug','Eigengewicht'),('Bird Dog','Eigengewicht'),('Ab-Wheel Rollout','Bauchroller'),('Woodchoppers (Kabelzug)','Kabelzug'),('Pallof Press','Kabelzug'),('Heel Touches','Eigengewicht'),('V-Ups','Eigengewicht'),('Flutter Kicks','Eigengewicht')]),
('Core','hold','time',[('Unterarmstütz','Eigengewicht'),('Seitstütz','Eigengewicht'),('Hollow Hold','Eigengewicht'),('Bear Plank','Eigengewicht'),('Copenhagen Plank','Bank'),('Wandsitzen','Eigengewicht')]),
('Ganzkörper','conditioning','reps',[('Burpees','Eigengewicht'),('Mountain Climbers','Eigengewicht'),('Kettlebell Swings','Kettlebell'),('Thrusters (Kurzhanteln)','Kurzhanteln'),('Wall Balls','Medizinball'),('Box Jumps','Box'),('Jump Squats','Eigengewicht'),('Medicine Ball Slams','Medizinball'),('Kettlebell Clean','Kettlebell'),('Turkish Get-up','Kettlebell')]),
('Ganzkörper','carry','distance',[('Farmer Walk','Kurzhanteln'),('Suitcase Carry','Kettlebell'),('Schlitten schieben','Schlitten'),('Schlitten ziehen','Schlitten')]),
('Ausdauer','cardio','distance',[('Laufband','Laufband'),('Laufen draußen','Keines'),('Gehen','Keines'),('Laufband mit Steigung','Laufband'),('Fahrradergometer','Ergometer'),('Spinning','Spinning-Bike'),('Radfahren draußen','Fahrrad'),('Ruderergometer','Ruderergometer'),('Crosstrainer','Crosstrainer'),('Air Bike','Air Bike'),('SkiErg','SkiErg'),('Schwimmen','Schwimmbad')]),
('Ausdauer','cardio','time',[('Stairmaster','Stairmaster'),('Seilspringen','Springseil'),('Battle Ropes','Seile'),('Jumping Jacks','Eigengewicht'),('High Knees','Eigengewicht'),('Shadow Boxing','Keines')])
]
recipes = {
'press':['Nimm eine stabile Position ein und halte Handgelenke über den Unterarmen.','Senke das Gewicht kontrolliert in deinem gut kontrollierbaren Bewegungsradius.','Drücke gleichmäßig nach vorne bzw. oben und behalte die Spannung im Rumpf.'],
'fly':['Stabilisiere den Oberkörper und beuge die Ellbogen leicht.','Führe die Arme in einem Bogen vor dem Körper zusammen.','Öffne kontrolliert, ohne die Schultern nach vorne kippen zu lassen.'],
'pushup':['Stütze die Hände stabil auf und spanne Bauch und Gesäß an.','Senke den Körper als Einheit, Ellbogen schräg nach hinten.','Drücke dich wieder hoch, ohne die Hüfte durchhängen zu lassen.'],
'dip':['Greife die Holme und stabilisiere die Schultern.','Beuge die Ellbogen und senke dich nur so weit, wie du die Position kontrollierst.','Drücke dich ohne Schwung nach oben.'],
'row':['Stabilisiere Rumpf und Wirbelsäule in der passenden Ausgangsposition.','Ziehe die Ellbogen nach hinten und das Gewicht zum Oberkörper.','Lass die Arme kontrolliert wieder lang werden, ohne im Rücken zu schwingen.'],
'pulldown':['Wähle den angegebenen Griff und halte den Rumpf ruhig.','Ziehe die Ellbogen nach unten; beim Klimmzug bewegst du den Körper zur Stange.','Kehre langsam in die Ausgangsposition zurück. Bei Scapular Pull-ups bleiben die Arme lang.'],
'pullover':['Stabilisiere Rumpf und Schultern und beuge die Ellbogen leicht.','Bewege die Arme aus der Überkopfposition in Richtung Körper.','Führe sie kontrolliert zurück, ohne den Rücken stark zu überstrecken.'],
'backextension':['Richte die Auflage passend ein bzw. nimm die Bauchlage ein.','Hebe Oberkörper oder Beine kontrolliert bis zur Linie des Körpers.','Senke langsam ab, ohne ins Hohlkreuz zu drücken.'],
'overhead':['Spanne Bauch und Gesäß an und bringe die Hände in die Druckposition.','Drücke kontrolliert über den Kopf; bei Pike Push-ups bewegt sich der Körper.','Kehre ohne Schwung zurück und halte den Rumpf stabil.'],
'raise':['Halte den Oberkörper ruhig und die Ellbogen leicht gebeugt.','Hebe die Arme seitlich oder nach vorn entsprechend der Variante.','Senke langsam ab und vermeide Schwung aus dem Rücken.'],
'reversefly':['Wähle einen leichten Widerstand und stabilisiere den Rumpf.','Führe die Arme nach außen bzw. beim Face Pull zum Gesicht. Bei Außenrotation bleiben die Ellbogen am Körper.','Kehre langsam zurück, ohne die Schultern hochzuziehen.'],
'shrug':['Stehe aufrecht mit dem Gewicht seitlich oder vor dem Körper.','Hebe die Schultern senkrecht an; rolle sie nicht im Kreis.','Senke sie kontrolliert wieder ab.'],
'curl':['Stabilisiere die Oberarme und halte die Handgelenke gerade.','Beuge die Ellbogen mit dem für die Variante vorgesehenen Griff.','Senke den Widerstand langsam, ohne mit dem Oberkörper nachzuhelfen.'],
'triceps':['Halte die Oberarme in der zur Variante passenden Position ruhig.','Strecke die Ellbogen kontrolliert gegen den Widerstand.','Beuge sie wieder, ohne die Schultern mitzubewegen.'],
'wrist':['Stütze die Unterarme und halte den Widerstand kontrolliert.','Bewege Handgelenke oder Finger entsprechend dem Gerät.','Kehre langsam zurück; nutze einen kleinen, kontrollierten Bewegungsradius.'],
'hold':['Nimm eine stabile Ausgangsposition für die Übung ein.','Halte die Position mit gleichmäßiger Atmung und Spannung.','Beende den Satz, sobald du die Position nicht mehr kontrolliert halten kannst.'],
'squat':['Stelle die Füße stabil auf und spanne den Rumpf an.','Beuge Hüfte und Knie; führe die Knie in Richtung der Zehen.','Drücke dich aus dem ganzen Fuß hoch und halte den Rücken stabil.'],
'legpress':['Stelle Sitz und Lehne ein und platziere beide Füße stabil.','Beuge die Knie kontrolliert, solange das Becken auf der Auflage bleibt.','Drücke die Plattform weg, ohne die Knie schwungvoll durchzuschlagen.'],
'lunge':['Stelle dich stabil hin und wähle die passende Schrittposition oder Stufe.','Senke den Körper kontrolliert; das belastete Knie folgt der Fußrichtung.','Drücke dich über das Arbeitsbein zurück. Wiederholungen je Seite erfassen.'],
'legextension':['Stelle Polster und Drehpunkt passend zu deinen Knien ein.','Strecke die Knie kontrolliert; beim Reverse Nordic bleibt die Hüfte gestreckt.','Kehre langsam in die Ausgangsposition zurück.'],
'hinge':['Stelle dich stabil auf, spanne den Rumpf an und halte das Gewicht nah am Körper.','Schiebe die Hüfte nach hinten und beuge die Knie passend zur Variante.','Strecke die Hüfte kontrolliert, ohne am oberen Punkt ins Hohlkreuz zu gehen.'],
'legcurl':['Stelle die Auflage ein oder sichere die Füße entsprechend der Variante.','Beuge die Knie gegen den Widerstand; bei Nordic Curls kontrollierst du das Absenken.','Führe die Bewegung langsam zurück und halte die Hüfte stabil.'],
'bridge':['Positioniere Füße und obere Rückenauflage stabil.','Hebe die Hüfte durch Druck aus den Füßen und spanne das Gesäß an.','Senke kontrolliert ab, ohne den unteren Rücken zu überstrecken.'],
'hip':['Stabilisiere Becken und Oberkörper.','Bewege das Arbeitsbein nach außen, innen oder hinten entsprechend der Variante.','Kehre langsam zurück, ohne das Becken mitzudrehen.'],
'calf':['Stelle die Füße stabil auf und nutze bei Bedarf eine Stütze.','Hebe die Fersen; bei Tibialis Raises hebst du stattdessen die Fußspitzen.','Senke kontrolliert und vermeide federnde Bewegungen.'],
'crunch':['Richte die Ausgangsposition stabil ein und spanne den Bauch an.','Bewege Rumpf oder Beine kontrolliert; bei Dead Bug und Bird Dog bleibt der Rumpf ruhig.','Kehre ohne Schwung zurück. Bei Pallof Press hältst du gegen die Rotation.'],
'conditioning':['Wähle einen Widerstand bzw. eine Höhe, die du sicher beherrschst.','Führe jede Wiederholung bewusst aus und behalte bei zunehmendem Tempo die Kontrolle.','Unterbrich den Satz, wenn die Bewegung unsauber wird. Bei komplexen Übungen Technik vorher erlernen.'],
'carry':['Greife den Widerstand stabil bzw. nimm eine sichere Schlittenposition ein.','Bewege dich mit kontrollierten Schritten und gleichmäßigem Rumpf.','Notiere die zurückgelegte Strecke und die Dauer des Satzes.'],
'cardio':['Stelle das Gerät passend ein bzw. wähle eine geeignete Strecke.','Beginne ruhig und steigere auf dein geplantes Tempo.','Notiere Dauer und, falls sinnvoll, Strecke; beende die Belastung mit ruhigem Tempo.']}
items=[]
for muscle,pattern,kind,exercises in groups:
 for name,equipment in exercises:
  items.append(dict(id=f'ex-{len(items)+1:03}',name=name,muscle=muscle,equipment=equipment,kind=kind,instructions=recipes[pattern],pattern=pattern))
assert 200<=len(items)<=300, len(items)
assert len({x['name'] for x in items})==len(items)
Path('/workspace/sites/setwerk/dist/exercises.js').write_text('/* Setwerk: eigener Übungskatalog, Version 1. */\nwindow.GYM_EXERCISES = '+json.dumps(items,ensure_ascii=False,separators=(',',':'))+';\n')
print(f'{len(items)} eindeutige Übungen erstellt')
